server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: 123456
logging:
  level:
    web: debug
    org.zjsru: debug